stateDiagram
  direction LR
  state BuscarDevice {
    direction TB
    [*] --> ConsultarBancoDados
    ConsultarBancoDados --> DeviceEncontrado:Sucesso
    ConsultarBancoDados --> DeviceNaoEncontrado:Erro
    DeviceNaoEncontrado --> SalvarLogDevice:Device não encontrado
    SalvarLogDevice --> [*]:Erro
    DeviceEncontrado --> [*]:Sucesso
[*]    ConsultarBancoDados
    DeviceEncontrado
    DeviceNaoEncontrado
    SalvarLogDevice
[*]  }
  state BuscarEmpresa {
    direction TB
    [*] --> ConsultarInfoEmpresa
    ConsultarInfoEmpresa --> EmpresaEncontrada:Sucesso
    ConsultarInfoEmpresa --> EmpresaNaoEncontrada:Erro
    EmpresaNaoEncontrada --> SalvarLogEmpresa:Empresa não encontrada
    SalvarLogEmpresa --> [*]:Erro
    EmpresaEncontrada --> [*]:Sucesso
[*]    ConsultarInfoEmpresa
    EmpresaEncontrada
    EmpresaNaoEncontrada
    SalvarLogEmpresa
[*]  }
  state EnviarPost {
    direction TB
    [*] --> ValidarURLEmpresa
    ValidarURLEmpresa --> URLInvalida:URL inválida
    URLInvalida --> SalvarLogURL:Registrar erro
    SalvarLogURL --> [*]:Erro
    ValidarURLEmpresa --> RealizarRequest:URL válida
    RealizarRequest --> RequestSucesso:Sucesso
    RealizarRequest --> RequestFalha:Erro
    RequestFalha --> SalvarLogRequest:Registrar erro
    SalvarLogRequest --> [*]:Erro
    RequestSucesso --> [*]:Sucesso
[*]    ValidarURLEmpresa
    URLInvalida
    SalvarLogURL
[*]    RealizarRequest
    RequestSucesso
    RequestFalha
    SalvarLogRequest
  }
  [*] --> ReceberMensagemMQTT:Mensagem do Iris
  ReceberMensagemMQTT --> DecodificarFlatbuffer:Mensagem Recebida
  DecodificarFlatbuffer --> ErroDecodificacao:Erro
  ErroDecodificacao --> SalvarLogDecodificacao:Falha na decodificação
  SalvarLogDecodificacao --> [*]:Processo Finalizado com Erro
  DecodificarFlatbuffer --> CriarEvento:Sucesso
  CriarEvento --> BuscarDevice:ID do Device
  BuscarDevice --> ErroDevice:Device não encontrado
  ErroDevice --> SalvarLogDevice2:Registrar erro
  SalvarLogDevice2 --> [*]:Processo Finalizado com Erro
  BuscarDevice --> BuscarEmpresa:Device Encontrado
  BuscarEmpresa --> ErroEmpresa:Empresa não encontrada
  ErroEmpresa --> SalvarLogEmpresa2:Registrar erro
  SalvarLogEmpresa2 --> [*]:Processo Finalizado com Erro
  BuscarEmpresa --> ConverterDados:Empresa Encontrada
  ConverterDados --> ErroConversao:Erro na conversão
  ErroConversao --> SalvarLogConversao:Registrar erro
  SalvarLogConversao --> [*]:Processo Finalizado com Erro
  ConverterDados --> EnviarPost:Dados Convertidos com Sucesso
  EnviarPost --> ErroPost:Falha no envio
  ErroPost --> SalvarLogPost:Registrar erro
  SalvarLogPost --> [*]:Processo Finalizado com Erro
  EnviarPost --> [*]:Processo Finalizado com Sucesso


