@startuml
left to right direction

actor User as "Usuário"
actor Admin as "Administrador"
entity Gateway

package "Sistema Midfield" {
    usecase UC1 as "Processamento de Mensagens"
    usecase UC2 as "Gerenciar Empresas"
    usecase UC3 as "Gerenciar Aplicativos"
    usecase UC4 as "Gerenciar Webhook/MQTT"
    usecase UC5 as "Gerenciar Gateways Iris"
    usecase UC6 as "Gerenciar Gateways Hermes"
    usecase UC7 as "Gerenciar Sensores"
    usecase UC8 as "Visualizar Eventos"
    usecase UC9 as "Gerenciar Usuários"
    usecase UC10 as "Visualizar Dashboard"
}

Admin --> UC2
Admin --> UC3
Admin --> UC4
Admin --> UC5
Admin --> UC6
Admin --> UC7
Admin --> UC8
Admin --> UC9

User --> UC8
User --> UC10

Gateway --> UC1
@enduml